# -*- coding: utf-8 -*-
"""Data_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iYByYOVXJBIeDmNIbnyFNWqb2E9-_FCF
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

sdata = pd.read_csv("Data.csv")
X = sdata.iloc[: , :-1].values
Y = sdata.iloc[:, 3].values

from sklearn.preprocessing import Imputer
imp = Imputer(missing_values = 'NaN', axis = 0)
imp = imp.fit(X[:, 1:3])
X[:, 1:3] = imp.transform(X[:, 1:3])

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_X = LabelEncoder()
X[:, 0] = le_X.fit_transform(X[:, 0])
ohe = OneHotEncoder(categorical_features = [0])
X = ohe.fit_transform(X).toarray()
le_Y = LabelEncoder()
Y = le_Y.fit_transform(Y)

from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
scX = StandardScaler()
Xtrain = scX.fit_transform(Xtrain)
Xtest = scX.transform(Xtest)

print(Xtrain)
print(Y)