# -*- coding: utf-8 -*-
"""Simple_Linear_Regression_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16F44dXvbvKbHrCByxM4Epx39rFw06Q4T

AUTHOR = AMLAN MUKHERJEE
"""

# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/My Drive/"

!cp "/content/drive/My Drive/Salary_Data.csv" "Salary_Data.csv"

!ls

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

ds = pd.read_csv("Salary_Data.csv")
X = ds.iloc[:, :-1]
Y = ds.iloc[:, 1]

from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size = 1/3, random_state = 0)

from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(Xtrain, Ytrain)

Ypred = reg.predict(Xtest)

plt.scatter(Xtrain, Ytrain, color = "red")
plt.plot(Xtrain, reg.predict(Xtrain), color = "black")
plt.title("Salary VS Experience (training set)")
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.show()

plt.scatter(Xtest, Ytest, color = "green")
plt.plot(Xtrain, reg.predict(Xtrain), color = "black")
plt.title("Salary VS Experience (test set)")
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.show()

# Difference between real and predicted values.
print(Ytest, "   ",Ypred)